USE [master]
GO

/****** Object:  Database [LvhK22CNT3Lesson07Db]    Script Date: 6/12/24 09:35:11 ******/
CREATE DATABASE [LvhK22CNT3Lesson07Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LvhK22CNT3Lesson07Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.LEVANHOANG\MSSQL\DATA\LvhK22CNT3Lesson07Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LvhK22CNT3Lesson07Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.LEVANHOANG\MSSQL\DATA\LvhK22CNT3Lesson07Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LvhK22CNT3Lesson07Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ARITHABORT OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET RECOVERY FULL 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET  MULTI_USER 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LvhK22CNT3Lesson07Db] SET  READ_WRITE 
GO

