//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhSinhVien
    {
        public string LvhMaSV { get; set; }
        public string LvhHoSV { get; set; }
        public string LvhTenSV { get; set; }
        public Nullable<System.DateTime> LvhNgaySinh { get; set; }
        public Nullable<bool> LvhPhai { get; set; }
        public string LvhPhone { get; set; }
        public string LvhEmail { get; set; }
        public string LvhMakH { get; set; }
    
        public virtual LvhKhoa LvhKhoa { get; set; }
    }
}
